[package]
name = "VideoReencodingNet"
version = "0.1.0"
edition = "2024"

[dependencies]
rocket = { version = "0.5.1", features = ["json"] }
serde = { version = "1.0.219", features = ["derive"] }
lazy_static = "1.5.0"
futures = "0.3.31"
clap = { version = "4.5.38", features = ["derive"] }
